name: Update Gist

on:
  push:
    branch: master

  schedule:
    - cron: "0 */3 * * *"

jobs:
  update-gist:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Install
        run: npm ci
      - name: Update gist
        run: node ./index.js
        env:
          GIST_TOKEN: ${{ secrets.GIST_TOKEN }}
          GIST_ID: a33ab2dec71825d648e84e9889008797
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
